name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-setuptools \
            python3-dev \
            git \
            openjdk-8-jdk \
            wget \
            unzip \
            zlib1g-dev \
            libncurses5-dev \
            libstdc++6 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libpng-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libunwind-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev

      - name: Install Buildozer
        run: |
          pip install buildozer
          pip install cython

      - name: Build APK
        run: |
          buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: bin/*.apk
