name: Build APK

on:
  push:
    branches:
      - main  # فرع GitHub الذي يتم بناء التطبيق عند دفع الكود إليه
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # الخطوة 1: استخراج الكود من المستودع
    - name: Checkout repository
      uses: actions/checkout@v3

    # الخطوة 2: إعداد Python و Buildozer
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev
        sudo apt install -y python3-pip virtualenv zip
        sudo apt install -y default-jdk git
        pip install --upgrade pip setuptools wheel
        pip install buildozer cython==0.29.33

    # الخطوة 3: بناء تطبيق APK باستخدام Buildozer
    - name: Build APK
      run: |
        sed -i 's/^requirements =.*/requirements = kivy/' buildozer.spec
        buildozer android debug

    # الخطوة 4: رفع ملف APK إلى نتائج الإصدار
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: myapp-debug.apk
        path: bin/*.apk
